# Region of Interest (ROI) settings
roi:
  find_roi: True
  micron_roi: 2000.0  # ROI size in microns
  center_x: 1200     # X center coordinate
  center_y: 1250     # Y center coordinate


# Pre-processing parameters
preprocessing:
  # All size parameters are now in microns
  gauss_sigma: 2.0  # Regular smoothing sigma in microns (for noise reduction)
  background_sigma: 3.0 #Background smoothing sigma in microns (for background estimation)
  median_filter_size: 3.0  # Median filter size in microns
  close_radius: 2.0  # Closing operation radius in microns
  min_object_size: 64  # Minimum object size to keep (in voxels)
  prune_length: 5  # Length to prune skeleton branches (in voxels)
  binarization_method: 'triangle'  # Method for binarization ('triangle' or 'otsu')


# Scale bar settings for plotting
scalebar:
  length: 25.0  # Length in plot units
  x: 15.0       # X position
  y: 200.0      # Y position