# Region of Interest (ROI) settings
roi:
  micron_roi: 200.0  # ROI size in microns
  center_x: 1200     # X center coordinate
  center_y: 1250     # Y center coordinate

# Scale bar settings for plotting
scalebar:
  length: 25.0  # Length in plot units
  x: 15.0       # X position
  y: 200.0      # Y position

# Pre-processing parameters
preprocessing:
  gauss_sigma: 0.75        # Gaussian smoothing sigma before Frangi/threshold
  min_object_size: 64     # Minimum object size to keep
  close_radius: 1.0     # Closing operation radius in voxels
  prune_length: 5         # Length to prune skeleton branches
  binarization_method: "triangle"  # "triangle" or "otsu"
  median_filter_size: 3   # Size of median filter to apply before binarization