# Region of Interest (ROI) settings
roi:
  find_roi: True
  micron_roi: 1000.0  # ROI size in microns
  min_x: 500     # X center coordinate
  min_y: 500     # Y center coordinate


# Pre-processing parameters
preprocessing:
  # All size parameters are now in microns
  gauss_sigma: 1.5  # Regular smoothing sigma in microns (for noise reduction)
  median_filter_size: 45.0  # Median filter size in microns
  close_radius: 2.0  # Closing operation radius in microns
  min_object_size: 64  # Minimum object size to keep (in voxels)
  prune_length: 5  # Length to prune skeleton branches (in voxels)
  binarization_method: 'triangle'  # Method for binarization ('triangle' or 'otsu')
  max_workers: null  # Number of worker threads for parallel processing. null = use default (CPU cores)

# Region detection parameters
region:
  peak_distance: 2  # Minimum distance between peaks in z-profile
  height_ratio: 0.80  # Relative height ratio for peak width calculation
  n_stds: 3.0 # Number of standard deviations for region boundaries

regions:
 - superficial
 - intermediate
 - deep

# Scale bar settings for plotting
scalebar:
  length: 25.0  # Length in plot units
  x: 15.0       # X position
  y: 200.0      # Y position

# Verbosity level (1-3)
verbose: 2